ci/ui: enable prime and rancher 2.9-head in UI
rancher/elemental pull request #1495
Opened 2024-07-16 14:35 UTC by juadk

Fix #1491 

## Verification runs
TBD

2024-07-22 09:45 UTC, juadk commented
![image](https://github.com/user-attachments/assets/9277bc39-235a-468d-9436-d2f6d155ec26)

I have to put this `registry.opensuse.org/isv/rancher/elemental/dev/containers` instead of `registry.rancher.com`

2024-07-23 08:01 UTC, ldevulder requested changes
LGTM, just a small comment.

2024-07-23 08:01 UTC, ldevulder commented on tests/cypress/latest/support/elemental.ts
> +        .type('registry.opensuse.org/isv/rancher/elemental/dev/containers');
Maybe just a comment to explain why it is hardcoded (as there is a good reason ;-)).

2024-07-23 08:06 UTC, ldevulder approved these changes

2024-07-23 08:07 UTC, merged