[WIP] Docusaurus installed and docs migrated
rancher/elemental pull request #272
Opened 2022-08-12 16:47 UTC by nunix

Docusaurus installed and initial configuration done:
- Elemental sidebar created to match the mkdocs side bar.
- Header links set and logo is missing
- Footer created with same links from mkdocs

The docs have been migrated 1:1 without any adaptation, so expect view glitches.

2022-08-30 09:40 UTC, nunix commented
Commit [9f0204f](https://github.com/rancher/elemental/pull/272/commits/9f0204f9db2daead90d61fc4157d50b9d251e9e8) also added:

- Plugin `raw-loader` has been added for loading YAML and JSON files content
- `CodeBlock` module has been added as a Global module (same as Tabs and TabItem)

2022-10-04 08:25 UTC, kkaempf commented
No update from @nunix - moving to blocked

2022-10-27 15:33 UTC, kkaempf requested changes
I don't think `.docusaurus` should be under git control as it contains generated files.

2022-10-27 15:37 UTC, kkaempf commented
Please also consider https://github.com/nunix/elemental-docs/pull/4 and https://github.com/nunix/elemental-docs/pull/5

2022-10-27 15:43 UTC, kkaempf commented
The files in `img` need a LICENSE and probably author attributions.

2022-10-27 15:46 UTC, kkaempf commented
`src/theme` seems to come from upstream (?) and shouldn't be checked into git. If we can't pull these files at buildtime, they need a license and proper attribution.

2022-10-27 15:50 UTC, kkaempf commented
I also wonder if we shouldn't take this move to docusaurus as an opportunity to migrate all docs (elemental, elemental-operator, elemental-toolkit) into a single, new repository `elemental-docs` 🤔

2022-10-28 08:19 UTC, nunix commented
> `src/theme` seems to come from upstream (?) and shouldn't be checked into git. If we can't pull these files at buildtime, they need a license and proper attribution.

@kkaempf this directory is needed for the global variables, it's indeed Docusaurus content, but adapted to Elemental.

2022-10-28 08:42 UTC, kkaempf commented
> > `src/theme` seems to come from upstream (?) and shouldn't be checked into git. If we can't pull these files at buildtime, they need a license and proper attribution.
> 
> @kkaempf this directory is needed for the global variables, it's indeed Docusaurus content, but adapted to Elemental.

If it's coming from Docusaurus, it needs to me mentioned in a (toplevel?) license file with proper attribution. What does Docusaurus say about including theme files ?

2022-10-28 08:51 UTC, kkaempf requested changes
The docusaurus content (theme and `png`s) needs proper licensing and attribution

2022-10-28 08:52 UTC, kkaempf commented
Merging this will immediately break docs creation on https://rancher.github.io/elemental, no ?

2022-10-28 09:02 UTC, nunix commented
> > > `src/theme` seems to come from upstream (?) and shouldn't be checked into git. If we can't pull these files at buildtime, they need a license and proper attribution.
> > 
> > 
> > @kkaempf this directory is needed for the global variables, it's indeed Docusaurus content, but adapted to Elemental.
> 
> If it's coming from Docusaurus, it needs to me mentioned in a (toplevel?) license file with proper attribution. What does Docusaurus say about including theme files ?

Docusaurus has an MIT license (https://github.com/rancher/elemental/pull/272#issuecomment-1294709443) and concerning the theme files, this is part of the product itself and usable by the end-users.

More precisely, concerning the directory above, it has been created using a Docusaurus features: https://docusaurus.io/docs/swizzling and it's even encouraged in their own docs: https://docusaurus.io/docs/markdown-features/react#mdx-component-scope.

2022-10-28 09:07 UTC, nunix commented
> Merging this will immediately break docs creation on https://rancher.github.io/elemental, no ?

yes, the GH action still needs to be adapted for Docusaurus (I'll check with someone in the team)

2022-10-31 12:30 UTC, Itxaka approved these changes

2022-10-31 13:03 UTC, kkaempf requested changes

2022-10-31 13:03 UTC, kkaempf commented on docs/cluster-reference.md
> +The example below creates a cluster that uses 2 different `machinePools` to set different nodes to control-plane and workers nodes,
```suggestion
The example below creates a cluster that uses 2 different `machinePool`s to set different nodes to control-plane and workers nodes,
```

2022-10-31 14:34 UTC, mjura approved these changes
LGTM

2022-10-31 14:52 UTC, kkaempf approved these changes
Ship it !

2022-10-31 14:55 UTC, merged