Don't use wget in elemental-iso-add-registration
rancher/elemental pull request #641
Opened 2023-01-30 14:25 UTC by cbosdo

The rationale behind this change is that wget is not shipped with SLE Micro while curl is.

2023-01-30 14:28 UTC, davidcassany commented
> The rationale behind this change is that wget is not shipped with SLE Micro while curl is.

Thanks! :+1:

2023-01-30 14:28 UTC, davidcassany approved these changes

2023-01-30 15:46 UTC, fgiudici requested changes
Thanks for the PR!
One little change required :-)

2023-01-30 15:46 UTC, fgiudici commented on .github/elemental-iso-add-registration
> +      curl -o "${TEMPDIR}/iso/${ISO_FILE}" "${ISO_URL}"
`download.opensuse.org/repositories/...` will be redirected to `ftp.gwdg.de/pub/opensuse/repositories/`-
So, you mean the curl -L option here :-) 
```suggestion
      curl -Lo "${TEMPDIR}/iso/${ISO_FILE}" "${ISO_URL}"
```

2023-01-30 17:15 UTC, fgiudici approved these changes
looks good, thanks!

2023-02-24 08:47 UTC, ldevulder commented
What I don't like is that `curl` doesn't do retry and we have sporadic download issue with opensuse.org regularly...

2023-06-30 11:09 UTC, merged