ci/ui: add UI upgrade test back
rancher/elemental pull request #683
Opened 2023-02-20 16:01 UTC by juadk

Fix #659

2023-02-21 14:09 UTC, juadk commented
In the meantime, I'm trying to check if we can remove the workaround we have for upgrade (restart fleet controller and fleet agent).
First test without it ok: https://github.com/rancher/elemental/actions/runs/4233167479
But as it was sporadic, I need to trigger more runs to validate.

2023-02-22 15:34 UTC, juadk commented
Finally, without the workaround, it's still failing sometimes so I will keep it for now.
I will continue my investigations later.

2023-02-23 08:46 UTC, ldevulder requested changes
2 small fixes to do.

2023-02-23 08:46 UTC, ldevulder commented on .github/workflows/ui-k3s-os-upgrade.yaml
> +      upgrade_image: registry.opensuse.org/isv/rancher/elemental/${{ inputs.upgrade_os_channel }}/teal53/15.4/rancher/elemental-teal/5.3:latest
`upgrade_os_channel` is not defined in the `inputs`.

2023-02-23 08:46 UTC, ldevulder commented on .github/workflows/ui-rke2-os-upgrade.yaml
> +      upgrade_image: registry.opensuse.org/isv/rancher/elemental/${{ inputs.upgrade_os_channel }}/teal53/15.4/rancher/elemental-teal/5.3:latest
`upgrade_os_channel` is not defined in the `inputs`.

2023-02-23 08:59 UTC, ldevulder approved these changes

2023-02-23 09:13 UTC, merged