ci: install as simple application
rancher/elemental pull request #897
Opened 2023-07-04 14:06 UTC by ldevulder

Install a simple application and check it in different upgrade scenari.

Should fix #700.

Verification runs:
- [CLI-OBS-Manual-Workflow](https://github.com/rancher/elemental/actions/runs/5455644206)

2023-07-05 14:58 UTC, kkaempf approved these changes
lgtm

2023-07-11 07:13 UTC, juadk requested changes
LGTM, only a small typo to change.

2023-07-11 07:13 UTC, juadk commented on .github/workflows/cli-rke2-obs_staging.yaml
> +      luster_type: ${{ inputs.cluster_type }}
```suggestion
      cluster_type: ${{ inputs.cluster_type }}
```

2023-07-11 07:26 UTC, ldevulder commented on .github/workflows/cli-rke2-obs_staging.yaml
> +      luster_type: ${{ inputs.cluster_type }}
Fixed, thanks!

2023-07-11 07:33 UTC, juadk approved these changes

2023-07-11 07:43 UTC, merged